/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.GUIUtil.CambiaPanel;
import Logic.ArchivoUsuarios;
import Logic.Usuario;
import Logic.Administrador;
import Logic.Progreso;
import Logic.Tutor;
import java.awt.*;
import javax.swing.*;
import org.json.JSONObject;

/**
 *
 * @author Angel
 */
public class Menu extends javax.swing.JFrame {

    private static Usuario usuario;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        new CambiaPanel(jPanel3,new Area1("A1"));
        
        if(usuario instanceof Administrador){
            admin.setVisible(true);
        }
        else{
            admin.setVisible(false);
        }
        ImageIcon icono = new ImageIcon("icon/logo.png");
        jLogo.setIcon(icono);
    }

    public static void setUsuario(Usuario usuario) {
        Menu.usuario = usuario;
        Area1.setUsuario(usuario);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        admin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bA5 = new javax.swing.JButton();
        jMenu = new javax.swing.JLabel();
        bA2 = new javax.swing.JButton();
        bA3 = new javax.swing.JButton();
        bA4 = new javax.swing.JButton();
        bA6 = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();
        bA7 = new javax.swing.JButton();
        bA8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lUser.setText("Hola: USUARIO !");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        admin.setBackground(new java.awt.Color(153, 255, 153));
        admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                .addComponent(admin)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUser)
                    .addComponent(admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        bA5.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA5.setForeground(new java.awt.Color(255, 102, 153));
        bA5.setText("Área I");
        bA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA5ActionPerformed(evt);
            }
        });

        jMenu.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("MENÚ");

        bA2.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA2.setForeground(new java.awt.Color(102, 204, 0));
        bA2.setText("Área II");
        bA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA2ActionPerformed(evt);
            }
        });

        bA3.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA3.setForeground(new java.awt.Color(0, 204, 204));
        bA3.setText("Área III");
        bA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA3ActionPerformed(evt);
            }
        });

        bA4.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA4.setForeground(new java.awt.Color(153, 102, 255));
        bA4.setText("Área IV");
        bA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA4ActionPerformed(evt);
            }
        });

        bA6.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA6.setForeground(new java.awt.Color(153, 153, 153));
        bA6.setText("Configuración");
        bA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA6ActionPerformed(evt);
            }
        });

        jLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bA7.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA7.setForeground(new java.awt.Color(204, 51, 0));
        bA7.setText("Salir");
        bA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA7ActionPerformed(evt);
            }
        });

        bA8.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA8.setForeground(new java.awt.Color(102, 51, 0));
        bA8.setText("Historial");
        bA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bA8, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(bA5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jMenu)
                .addGap(49, 49, 49)
                .addComponent(bA5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(bA8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA2ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jPanel3,new Area1("A2"));
    }//GEN-LAST:event_bA2ActionPerformed

    private void bA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA3ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jPanel3,new Area1("A3"));
    }//GEN-LAST:event_bA3ActionPerformed

    private void bA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA4ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jPanel3,new Area1("A4"));
    }//GEN-LAST:event_bA4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lUser.setText("Hola " + usuario.getNombre() + "!");
    }//GEN-LAST:event_formWindowOpened

    private void bA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA5ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jPanel3,new Area1("A1"));
    }//GEN-LAST:event_bA5ActionPerformed

    private void bA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA6ActionPerformed
        UserConfig.setUsuario(usuario); // Configura el usuario en la clase Menu
        GUIUtil.abrirVentana(UserConfig.class, this);
    }//GEN-LAST:event_bA6ActionPerformed

    private void bA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA7ActionPerformed
        // TODO add your handling code here:
        System.out.println("Llegué con: " + usuario.getTipoUsuario().toString());
        JSONObject usuarios = new JSONObject();

        usuarios.put("contraseña", usuario.getContraseña());
        usuarios.put("correo", usuario.getCorreo());
        usuarios.put("nombre", usuario.getNombre());
        usuarios.put("fechaNacimiento", usuario.getFechaNacimiento());
        usuarios.put("sexo", usuario.getSexo());
        usuarios.put("id", usuario.getId());
        usuarios.put("tUser", usuario.getTipoUsuario());
        if (usuario instanceof Tutor) {
            Tutor tutor = (Tutor) usuario; // Convertir usuario a Tutor
            usuarios.put("Materia", tutor.getMateria()); 
            System.out.println("Materia del PROFE!");
         }
         else{
            System.out.println("Materia como NA!");
            usuarios.put("Materia","Na");
         }

        // Busca si el usuario ya existe por correo
        boolean encontrado = ArchivoUsuarios.buscarUsuarioPorCorreo(usuario.getCorreo());
        if (encontrado) {
            // Si el usuario ya existe, actualiza los datos
            boolean actualizado = ArchivoUsuarios.actualizarUsuarioPorCorreo(usuario.getCorreo(), usuarios);
            if (actualizado) {
                System.out.println("Usuario actualizado correctamente.");
            } else {
                System.out.println("No encontrado correctamente.");
            }
        } else {
            // Si el usuario no existe, lo guarda como un nuevo usuario
            ArchivoUsuarios.guardarUsuario(usuarios);
            System.out.println("Usuario guardado correctamente.");
        }
        dispose();
    }//GEN-LAST:event_bA7ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        if(admin.getText().equals("Usuario")){
            admin.setText("Admin");
        }
        else{
            admin.setText("Usuario");
        }
        
    }//GEN-LAST:event_adminActionPerformed

    private void bA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA8ActionPerformed
        // TODO add your handling code here:
        usuario.mostrarHistorialProgreso();
    }//GEN-LAST:event_bA8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton bA2;
    private javax.swing.JButton bA3;
    private javax.swing.JButton bA4;
    private javax.swing.JButton bA5;
    private javax.swing.JButton bA6;
    private javax.swing.JButton bA7;
    private javax.swing.JButton bA8;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lUser;
    // End of variables declaration//GEN-END:variables
}
