/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.ArchivoUsuarios;
import Logic.Usuario;
import org.json.JSONObject;

/**
 *
 * @author Angel
 */
public class Menu extends javax.swing.JFrame {

    private static Usuario usuario;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public static void setUsuario(Usuario usuario) {
        Menu.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bA5 = new javax.swing.JButton();
        jMenu = new javax.swing.JLabel();
        bA2 = new javax.swing.JButton();
        bA3 = new javax.swing.JButton();
        bA4 = new javax.swing.JButton();
        bA6 = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();
        bA7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lUser.setText("Hola: USUARIO !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lUser)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lUser)
                .addContainerGap(557, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        bA5.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA5.setForeground(new java.awt.Color(255, 102, 153));
        bA5.setText("Área I");
        bA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA5ActionPerformed(evt);
            }
        });

        jMenu.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("MENÚ");

        bA2.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA2.setForeground(new java.awt.Color(102, 204, 0));
        bA2.setText("Área II");
        bA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA2ActionPerformed(evt);
            }
        });

        bA3.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA3.setForeground(new java.awt.Color(0, 204, 204));
        bA3.setText("Área III");
        bA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA3ActionPerformed(evt);
            }
        });

        bA4.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA4.setForeground(new java.awt.Color(153, 102, 255));
        bA4.setText("Área IV");
        bA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA4ActionPerformed(evt);
            }
        });

        bA6.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA6.setForeground(new java.awt.Color(153, 153, 153));
        bA6.setText("Configuración");
        bA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA6ActionPerformed(evt);
            }
        });

        jLogo.setText("LOGOTIPO");

        bA7.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        bA7.setForeground(new java.awt.Color(204, 51, 0));
        bA7.setText("Salir");
        bA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bA7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bA7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bA6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bA4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bA3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bA2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bA5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jMenu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLogo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jMenu)
                .addGap(49, 49, 49)
                .addComponent(bA5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bA7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bA2ActionPerformed

    private void bA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bA3ActionPerformed

    private void bA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bA4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lUser.setText("Hola " + usuario.getNombre() + "!");
    }//GEN-LAST:event_formWindowOpened

    private void bA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bA5ActionPerformed

    private void bA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA6ActionPerformed
        UserConfig.setUsuario(usuario); // Configura el usuario en la clase Menu
        GUIUtil.abrirVentana(UserConfig.class, this);
    }//GEN-LAST:event_bA6ActionPerformed

    private void bA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bA7ActionPerformed
        // TODO add your handling code here:
        JSONObject usuarios = new JSONObject();

        usuarios.put("contraseña", usuario.getContraseña());
        usuarios.put("correo", usuario.getCorreo());
        usuarios.put("nombre", usuario.getNombre());
        usuarios.put("fechaNacimiento", usuario.getFechaNacimiento());
        usuarios.put("sexo", usuario.getSexo());
        usuarios.put("id", usuario.getId());
        usuarios.put("tUser", usuario.getTipoUsuario());

        // Busca si el usuario ya existe por correo
        boolean encontrado = ArchivoUsuarios.buscarUsuarioPorCorreo(usuario.getCorreo());
        if (encontrado) {
            // Si el usuario ya existe, actualiza los datos
            boolean actualizado = ArchivoUsuarios.actualizarUsuarioPorCorreo(usuario.getCorreo(), usuarios);
            if (actualizado) {
                System.out.println("Usuario actualizado correctamente.");
            } else {
                System.out.println("No encontrado correctamente.");
            }
        } else {
            // Si el usuario no existe, lo guarda como un nuevo usuario
            ArchivoUsuarios.guardarUsuario(usuarios);
            System.out.println("Usuario guardado correctamente.");
        }
        dispose();
    }//GEN-LAST:event_bA7ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bA2;
    private javax.swing.JButton bA3;
    private javax.swing.JButton bA4;
    private javax.swing.JButton bA5;
    private javax.swing.JButton bA6;
    private javax.swing.JButton bA7;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lUser;
    // End of variables declaration//GEN-END:variables
}
