/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.ArchivoUsuarios;
import Logic.Usuario;
import java.text.SimpleDateFormat;
import java.util.*;
import org.json.JSONObject;

/**
 *
 * @author Angel
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tContra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        tFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vSexo = new javax.swing.JComboBox<>();
        bRegistro = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        vAlumno = new javax.swing.JComboBox<>();
        tError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Area1 = new javax.swing.JRadioButton();
        Area2 = new javax.swing.JRadioButton();
        Area3 = new javax.swing.JRadioButton();
        Area4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ravenscroft", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");

        tCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCorreoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");

        jCalendar1.setDate(new java.util.Date(1163904875000L));
        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        tFecha.setEditable(false);
        tFecha.setFocusable(false);
        tFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFechaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Sexo:");

        vSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "No Decir" }));
        vSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSexoActionPerformed(evt);
            }
        });

        bRegistro.setBackground(new java.awt.Color(255, 255, 204));
        bRegistro.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        bRegistro.setText("Registrar");
        bRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistroActionPerformed(evt);
            }
        });

        bRegresar.setBackground(new java.awt.Color(204, 0, 102));
        bRegresar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        bRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bRegresar.setText("Regresar");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Grado:");

        vAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor" }));
        vAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vAlumnoItemStateChanged(evt);
            }
        });
        vAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAlumnoActionPerformed(evt);
            }
        });

        tError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        Area1.setBackground(new java.awt.Color(255, 255, 255));
        Area1.setText("Ciencias Físico-Matemáticas e Ingenierías");
        Area1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Area1ItemStateChanged(evt);
            }
        });
        Area1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Area1MouseClicked(evt);
            }
        });
        Area1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area1ActionPerformed(evt);
            }
        });

        Area2.setBackground(new java.awt.Color(255, 255, 255));
        Area2.setText("Ciencias Biológicas, Químicas y de la Salud");
        Area2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Area2ItemStateChanged(evt);
            }
        });
        Area2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Area2MouseClicked(evt);
            }
        });
        Area2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area2ActionPerformed(evt);
            }
        });

        Area3.setBackground(new java.awt.Color(255, 255, 255));
        Area3.setText("Ciencias Sociales");
        Area3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Area3ItemStateChanged(evt);
            }
        });
        Area3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Area3MouseClicked(evt);
            }
        });
        Area3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area3ActionPerformed(evt);
            }
        });

        Area4.setBackground(new java.awt.Color(255, 255, 255));
        Area4.setText("Humanidades y de las Artes");
        Area4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Area4ItemStateChanged(evt);
            }
        });
        Area4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Area4MouseClicked(evt);
            }
        });
        Area4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Area4)
                    .addComponent(Area3)
                    .addComponent(Area2)
                    .addComponent(Area1))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Area1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Area2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Area3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Area4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tContra, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bRegistro)
                        .addGap(48, 48, 48)
                        .addComponent(bRegresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(vSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(vAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistro)
                    .addComponent(bRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCorreoActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void tFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFechaActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        if (evt.getOldValue() != null) {
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            tFecha.setText(ff.format(jCalendar1.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendar1PropertyChange

    private void vSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vSexoActionPerformed

    private void bRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistroActionPerformed

        tError.setText("");
        JSONObject usuario = new JSONObject();
        String texto = tNombre.getText().charAt(0) + tFecha.getText() + "123";
        int anio = 2024;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date date = sdf.parse(tFecha.getText()); // Convierte el String a Date
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            anio = calendar.get(Calendar.YEAR); // Obtiene el año
            System.out.println("El año es: " + anio);
        } catch (Exception e) {
            System.out.println("Error al procesar la fecha: " + e.getMessage());
        }

        usuario.put("contraseña", tContra.getText());
        usuario.put("correo", tCorreo.getText().toUpperCase());
        usuario.put("nombre", tNombre.getText());
        usuario.put("fechaNacimiento", tFecha.getText());
        usuario.put("sexo", vSexo.getSelectedItem());
        usuario.put("id", texto);
        if(vAlumno.getSelectedIndex()==0){
            usuario.put("tUser", "Estudiante");
            usuario.put("Materia", "Na");
        }
        else{
            usuario.put("tUser", "Tutor");
            Usuario.Materia variable = Usuario.Materia.Na;
            if(Area1.isSelected()){
                variable = Usuario.Materia.A1;
            }
            else if(Area2.isSelected()){
                variable = Usuario.Materia.A2;
            }
            else if(Area3.isSelected()){
                variable = Usuario.Materia.A3;
            }
            else if(Area4.isSelected()){
                variable = Usuario.Materia.A4;
            }
            usuario.put("Materia", variable);
        }
        
        if ("".equals(tContra.getText()) || tCorreo.getText().length() < 5) {
            tError.setText("Contraseña no válida.\n Longitud mínima: 5.");
            return;
        } else if ("".equals(tCorreo.getText()) || !tCorreo.getText().contains("@")) {
            tError.setText("Correo no válido.");
            return;
        } else if ("".equals(tNombre.getText()) || tNombre.getText().length() < 5) {
            tError.setText("Ingrese un nombre real.");
            return;
        } else if (2024 - anio < 5 || 2024 - anio >= 125) {
            tError.setText("Edad inválida.");
            return;
        }
        else if(vAlumno.getSelectedIndex()==1 && !(Area1.isSelected()||Area2.isSelected()||Area3.isSelected() || Area4.isSelected())){
            tError.setText("Seleccione una especialidad.");
            return;
        }

        boolean encontrado = ArchivoUsuarios.buscarUsuarioPorCorreo(tCorreo.getText());
        if (encontrado) {
            tError.setText("Correo electrónico ya registrado.");
        } else {
            ArchivoUsuarios.guardarUsuario(usuario);
            System.out.println("Usuario Guardado");
        }

    }//GEN-LAST:event_bRegistroActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        // TODO add your handling code here:
        GUIUtil.abrirVentana(Login.class, this);
    }//GEN-LAST:event_bRegresarActionPerformed

    private void vAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAlumnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vAlumnoActionPerformed

    private void Area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area1ActionPerformed

    private void Area2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area2ActionPerformed

    private void Area3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area3ActionPerformed

    private void Area4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area4ActionPerformed

    private void vAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vAlumnoItemStateChanged
        // TODO add your handling code here:
        if(vAlumno.getSelectedIndex()==1){
            jPanel2.setVisible(true);
        }
        else{
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_vAlumnoItemStateChanged

    private void Area1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Area1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Area1ItemStateChanged

    private void Area2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Area2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Area2ItemStateChanged

    private void Area3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Area3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Area3ItemStateChanged

    private void Area4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Area4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Area4ItemStateChanged

    private void Area1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Area1MouseClicked
        // TODO add your handling code here:
        Area2.setSelected(false);
        Area3.setSelected(false);
        Area4.setSelected(false);
        
        Area1.setSelected(true);
    }//GEN-LAST:event_Area1MouseClicked

    private void Area2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Area2MouseClicked
        // TODO add your handling code here:
        Area2.setSelected(true);
        Area3.setSelected(false);
        Area4.setSelected(false);
        
        Area1.setSelected(false);
    }//GEN-LAST:event_Area2MouseClicked

    private void Area3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Area3MouseClicked
        // TODO add your handling code here:
        Area2.setSelected(false);
        Area3.setSelected(true);
        Area4.setSelected(false);
        
        Area1.setSelected(false);
    }//GEN-LAST:event_Area3MouseClicked

    private void Area4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Area4MouseClicked
        // TODO add your handling code here:
        Area2.setSelected(false);
        Area3.setSelected(false);
        Area4.setSelected(true);
        
        Area1.setSelected(false);
    }//GEN-LAST:event_Area4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Area1;
    private javax.swing.JRadioButton Area2;
    private javax.swing.JRadioButton Area3;
    private javax.swing.JRadioButton Area4;
    private javax.swing.JButton bRegistro;
    private javax.swing.JButton bRegresar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tContra;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JLabel tError;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTextField tNombre;
    private javax.swing.JComboBox<String> vAlumno;
    private javax.swing.JComboBox<String> vSexo;
    // End of variables declaration//GEN-END:variables
}
